project_name: osdctl

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - "GO111MODULE=on" # make sure to use go modules
      - "GOFLAGS=-mod=readonly -trimpath" # trimpath helps with producing verificable binaries
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/openshift/osdctl/cmd.GitCommit={{.ShortCommit}} -X github.com/openshift/osdctl/cmd.Version={{.Version}}
      - "-extldflags=-zrelro" # binary hardening: For further explanation look here: https://www.redhat.com/en/blog/hardening-elf-binaries-using-relocation-read-only-relro
      - "-extldflags=-znow"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'sha256sum.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: "openshift"
    name: "osdctl"
  prerelease: auto
