# Generated by go2rpm 1.15.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/openshift/osdctl
%global goipath         github.com/openshift/osdctl

%global common_description %{expand:
CLI for the OSD utilities.}

%global golicenses      LICENSE
%global godocs          README.md

BuildRequires:  git
Name:           osdctl
Release:        %autorelease
Summary:        CLI for the OSD utilities
License:        Apache-2.0
URL:            https://github.com/bergmannf/osdctl
Version:        @version@
Source:         %{url}/archive/v%{version}/osdctl-%{version}.tar.gz

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%description %{common_description}

%gopkg

%prep
%goprep -A

%if %{without bootstrap}
%generate_buildrequires
# %go_generate_buildrequires
%endif

%if %{without bootstrap}
%define gomodulesmode GO111MODULE=on
%build
%gobuild -o %{gobuilddir}/bin/osdctl %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc README.md
%{_bindir}/osdctl
%endif

%gopkgfiles

%changelog
%autochangelog
