// Code generated by MockGen. DO NOT EDIT.
// Source: listresources.go

// Package printer is a generated GoMock package.
package printer

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPrinter is a mock of Printer interface
type MockPrinter struct {
	ctrl     *gomock.Controller
	recorder *MockPrinterMockRecorder
}

// MockPrinterMockRecorder is the mock recorder for MockPrinter
type MockPrinterMockRecorder struct {
	mock *MockPrinter
}

// NewMockPrinter creates a new mock instance
func NewMockPrinter(ctrl *gomock.Controller) *MockPrinter {
	mock := &MockPrinter{ctrl: ctrl}
	mock.recorder = &MockPrinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPrinter) EXPECT() *MockPrinterMockRecorder {
	return m.recorder
}

// AddRow mocks base method
func (m *MockPrinter) AddRow(row []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRow", row)
}

// AddRow indicates an expected call of AddRow
func (mr *MockPrinterMockRecorder) AddRow(row interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRow", reflect.TypeOf((*MockPrinter)(nil).AddRow), row)
}

// Flush mocks base method
func (m *MockPrinter) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush
func (mr *MockPrinterMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockPrinter)(nil).Flush))
}
