// Code generated by MockGen. DO NOT EDIT.
// Source: pagerduty.go

// Package mock_pagerduty is a generated GoMock package.
package mock_pagerduty

import (
	context "context"
	reflect "reflect"

	go_pagerduty "github.com/PagerDuty/go-pagerduty"
	"go.uber.org/mock/gomock"
)

// MockpdClientInterface is a mock of pdClientInterface interface.
type MockpdClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockpdClientInterfaceMockRecorder
}

// MockpdClientInterfaceMockRecorder is the mock recorder for MockpdClientInterface.
type MockpdClientInterfaceMockRecorder struct {
	mock *MockpdClientInterface
}

// NewMockpdClientInterface creates a new mock instance.
func NewMockpdClientInterface(ctrl *gomock.Controller) *MockpdClientInterface {
	mock := &MockpdClientInterface{ctrl: ctrl}
	mock.recorder = &MockpdClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpdClientInterface) EXPECT() *MockpdClientInterfaceMockRecorder {
	return m.recorder
}

// ListIncidentsWithContext mocks base method.
func (m *MockpdClientInterface) ListIncidentsWithContext(arg0 context.Context, arg1 go_pagerduty.ListIncidentsOptions) (*go_pagerduty.ListIncidentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidentsWithContext", arg0, arg1)
	ret0, _ := ret[0].(*go_pagerduty.ListIncidentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidentsWithContext indicates an expected call of ListIncidentsWithContext.
func (mr *MockpdClientInterfaceMockRecorder) ListIncidentsWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidentsWithContext", reflect.TypeOf((*MockpdClientInterface)(nil).ListIncidentsWithContext), arg0, arg1)
}

// ListServicesWithContext mocks base method.
func (m *MockpdClientInterface) ListServicesWithContext(arg0 context.Context, arg1 go_pagerduty.ListServiceOptions) (*go_pagerduty.ListServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServicesWithContext", arg0, arg1)
	ret0, _ := ret[0].(*go_pagerduty.ListServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServicesWithContext indicates an expected call of ListServicesWithContext.
func (mr *MockpdClientInterfaceMockRecorder) ListServicesWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServicesWithContext", reflect.TypeOf((*MockpdClientInterface)(nil).ListServicesWithContext), arg0, arg1)
}
