// Code generated by MockGen. DO NOT EDIT.
// Source: pagerduty.go
//
// Generated by this command:
//
//	mockgen -source=pagerduty.go -package=mock -destination=mocks/pagerduty_mock.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pagerduty "github.com/PagerDuty/go-pagerduty"
	gomock "go.uber.org/mock/gomock"
)

// MockpdClientInterface is a mock of pdClientInterface interface.
type MockpdClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockpdClientInterfaceMockRecorder
	isgomock struct{}
}

// MockpdClientInterfaceMockRecorder is the mock recorder for MockpdClientInterface.
type MockpdClientInterfaceMockRecorder struct {
	mock *MockpdClientInterface
}

// NewMockpdClientInterface creates a new mock instance.
func NewMockpdClientInterface(ctrl *gomock.Controller) *MockpdClientInterface {
	mock := &MockpdClientInterface{ctrl: ctrl}
	mock.recorder = &MockpdClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpdClientInterface) EXPECT() *MockpdClientInterfaceMockRecorder {
	return m.recorder
}

// ListIncidentsWithContext mocks base method.
func (m *MockpdClientInterface) ListIncidentsWithContext(arg0 context.Context, arg1 pagerduty.ListIncidentsOptions) (*pagerduty.ListIncidentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidentsWithContext", arg0, arg1)
	ret0, _ := ret[0].(*pagerduty.ListIncidentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidentsWithContext indicates an expected call of ListIncidentsWithContext.
func (mr *MockpdClientInterfaceMockRecorder) ListIncidentsWithContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidentsWithContext", reflect.TypeOf((*MockpdClientInterface)(nil).ListIncidentsWithContext), arg0, arg1)
}

// ListServicesWithContext mocks base method.
func (m *MockpdClientInterface) ListServicesWithContext(arg0 context.Context, arg1 pagerduty.ListServiceOptions) (*pagerduty.ListServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServicesWithContext", arg0, arg1)
	ret0, _ := ret[0].(*pagerduty.ListServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServicesWithContext indicates an expected call of ListServicesWithContext.
func (mr *MockpdClientInterfaceMockRecorder) ListServicesWithContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServicesWithContext", reflect.TypeOf((*MockpdClientInterface)(nil).ListServicesWithContext), arg0, arg1)
}
