# Validate the goReleaser configuration

name: validate_goreleaser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate_goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: 'v1.21.2'
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
